Serialize nested object values (properly?)
caktus/django-jsx pull request #3
Opened 2017-10-03 17:53 UTC by vkurup

When I tried upgrading BF to Django 1.9, I upgraded to use the latest version of django-jsx (0.2.3), and ran into this test failure:
```
(bringfido) vkurup@caktus020:~/dev/bringfido(develop) $ python manage.py test --keepdb attraction.tests.test_views.TestViews.test_attraction_type_state
Using existing test database for alias 'default'...
E
======================================================================
ERROR: test_attraction_type_state (attraction.tests.test_views.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vkurup/dev/bringfido/attraction/tests/test_views.py", line 164, in test_attraction_type_state
    'state_slug': self.state.slug}))
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/test/client.py", line 503, in get
    **extra)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/test/client.py", line 304, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/test/client.py", line 380, in generic
    return self.request(**r)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/test/client.py", line 467, in request
    six.reraise(*exc_info)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vkurup/dev/bringfido/bringfido/utils.py", line 829, in _wrapped_view_func
    response = cache_page(timeout)(view_func)(request, *args, **kwargs)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vkurup/dev/bringfido/attraction/views.py", line 256, in view_state
    return render(request, 'attraction/state.html', ctx)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/vkurup/.virtualenvs/bringfido/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/vkurup/dev/django-jsx/django_jsx/templatetags/jsx.py", line 121, in render
    ctx = serialize_opportunistically(context, expressions)
  File "/home/vkurup/dev/django-jsx/django_jsx/templatetags/jsx.py", line 54, in serialize_opportunistically
    set_nested(ctx, expression, value)
  File "/home/vkurup/dev/django-jsx/django_jsx/templatetags/jsx.py", line 34, in set_nested
    set_nested(dictionary[elts[0]], new_key, value)
  File "/home/vkurup/dev/django-jsx/django_jsx/templatetags/jsx.py", line 26, in set_nested
    dictionary[elts[0]] = value
TypeError: 'State' object does not support item assignment
```

That specific template has this in its jsx block: `currentLocation={ctx.location ? ctx.location.full_name : null}`

So `location: <State object>` gets added to the dictionary, and then we try to set d['location']['full_name'] which obviously fails.

I'm not 100% sure of my solution, because it seems to clobber the top level object, but for our purposes, we only want the actual attribute value that gets sent into the React component. I confirmed that the previous version of django-jsx did this.

2017-10-04 17:24 UTC, ironfroggy requested changes

2017-10-04 17:24 UTC, ironfroggy commented on django_jsx/templatetags/jsx.py
> +        if not isinstance(dictionary.get(elts[0], None), dict):
can you add a comment about the need for this check?

2017-10-04 19:43 UTC, vkurup commented
I found a spot where a top level key could clobber the nested dictionary, now fixed.

2017-10-05 12:21 UTC, ironfroggy approved these changes

2017-10-05 19:21 UTC, merged